------------------------------------------------------------------------------
--  Copyright (c) 2026 by Paul Scherrer Institute, Switzerland
--  All rights reserved.
--  Authors: Radoslaw Rybaniec
------------------------------------------------------------------------------

------------------------------------------------------------
-- Testbench generated by TbGen.py
------------------------------------------------------------
-- see Library/Python/TbGenerator

------------------------------------------------------------
-- Libraries
------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;
use std.textio.all;

use work.psi_fix_pkg.all;
use work.psi_tb_textfile_pkg.all;

------------------------------------------------------------
-- Entity Declaration
------------------------------------------------------------
entity psi_fix_lowpass_iir_order1_conf_tb is
    generic(
        file_folder_g : string  := "../testbench/psi_fix_lowpass_iir_order1_conf_tb/Data";
        pipeline_g    : boolean := false
    );
end entity;

------------------------------------------------------------
-- Architecture
------------------------------------------------------------
architecture sim of psi_fix_lowpass_iir_order1_conf_tb is
    -- *** Fixed Generics ***
    constant in_fmt_c   : psi_fix_fmt_t := (1, 0, 15);
    constant out_fmt_c  : psi_fix_fmt_t := (1, 0, 14);
    constant int_fmt_c  : psi_fix_fmt_t := (1, 0, 24);
    constant coef_fmt_c : psi_fix_fmt_t := (1, 0, 17);

    -- *** TB Control ***
    signal   TbRunning          : boolean                  := True;
    signal   ProcessDone        : std_logic_vector(0 to 1) := (others => '0');
    constant AllProcessesDone_c : std_logic_vector(0 to 1) := (others => '1');
    constant TbProcNr_stimuli_c : integer                  := 0;
    constant TbProcNr_check_c   : integer                  := 1;

    -- *** DUT Signals ***
    signal InClk_sti   : std_logic                                               := '0';
    signal InRst_sti   : std_logic                                               := '1';
    signal InVld_sti   : std_logic                                               := '0';
    signal InDat_sti   : std_logic_vector(psi_fix_size(in_fmt_c) - 1 downto 0)   := (others => '0');
    signal InAlpha_sti : std_logic_vector(psi_fix_size(coef_fmt_c) - 1 downto 0) := (others => '0');
    signal OutVld_obs  : std_logic                                               := '0';
    signal OutDat_obs  : std_logic_vector(psi_fix_size(out_fmt_c) - 1 downto 0)  := (others => '0');

    constant MaxStrbRate : integer                := 3;
    -- column 0 = input data, column 1 = alpha coefficient
    signal   SigIn       : TextfileData_t(0 to 1) := (others => 0);
    signal   SigOut      : TextfileData_t(0 to 0) := (others => 0);

begin
    ------------------------------------------------------------
    -- DUT Instantiation
    ------------------------------------------------------------
    i_dut : entity work.psi_fix_lowpass_iir_order1_conf
        generic map(
            pipeline_g => pipeline_g,
            in_fmt_g   => in_fmt_c,
            out_fmt_g  => out_fmt_c,
            int_fmt_g  => int_fmt_c,
            coef_fmt_g => coef_fmt_c
        )
        port map(
            clk_i       => InClk_sti,
            rst_i       => InRst_sti,
            cfg_alpha_i => InAlpha_sti,
            vld_i       => InVld_sti,
            dat_i       => InDat_sti,
            vld_o       => OutVld_obs,
            dat_o       => OutDat_obs
        );

    ------------------------------------------------------------
    -- Testbench Control !DO NOT EDIT!
    ------------------------------------------------------------
    p_tb_control : process
    begin
        wait until InRst_sti = '0';
        wait until ProcessDone = AllProcessesDone_c;
        TbRunning <= false;
        wait;
    end process;

    ------------------------------------------------------------
    -- Clocks !DO NOT EDIT!
    ------------------------------------------------------------
    p_clock_clk_i : process
        constant Frequency_c : real := 100.0e6;
    begin
        while TbRunning loop
            wait for 0.5 * (1 sec) / Frequency_c;
            InClk_sti <= not InClk_sti;
        end loop;
        wait;
    end process;

    ------------------------------------------------------------
    -- Resets
    ------------------------------------------------------------
    p_rst_rst_i : process
    begin
        wait for 1 us;
        -- Wait for two clk edges to ensure reset is active for at least one edge
        wait until rising_edge(InClk_sti);
        wait until rising_edge(InClk_sti);
        InRst_sti <= '0';
        wait;
    end process;

    ------------------------------------------------------------
    -- Processes
    ------------------------------------------------------------
    -- *** stimuli ***
    InDat_sti   <= std_logic_vector(to_signed(SigIn(0), InDat_sti'length));
    InAlpha_sti <= std_logic_vector(to_signed(SigIn(1), InAlpha_sti'length));
    p_stimuli : process
    begin
        -- start of process !DO NOT EDIT
        wait until InRst_sti = '0';

        -- Apply Stimuli
        ApplyTextfileContent(Clk         => InClk_sti,
                             Rdy         => PsiTextfile_SigOne,
                             Vld         => InVld_sti,
                             Data        => SigIn,
                             Filepath    => file_folder_g & "/input.txt",
                             ClkPerSpl   => MaxStrbRate,
                             IgnoreLines => 1);

        -- end of process !DO NOT EDIT!
        ProcessDone(TbProcNr_stimuli_c) <= '1';
        wait;
    end process;

    -- *** check ***
    SigOut(0) <= to_integer(signed(OutDat_obs));
    p_check : process
    begin
        -- start of process !DO NOT EDIT
        wait until InRst_sti = '0';

        -- Check
        CheckTextfileContent(Clk         => InClk_sti,
                             Rdy         => PsiTextfile_SigUnused,
                             Vld         => OutVld_obs,
                             Data        => SigOut,
                             Filepath    => file_folder_g & "/output.txt",
                             IgnoreLines => 1);

        -- end of process !DO NOT EDIT!
        ProcessDone(TbProcNr_check_c) <= '1';
        wait;
    end process;

end;
